kind: pipeline
name: default

steps:
  - name: build
    image: plugins/hugo
  - name: deploy
    image: drillster/drone-rsync
    settings:
      user: debian
      recursive: true
      hosts: [ "ovh01.nobody.run" ]
      source: ./public/
      target: /var/www/blog/
      args: "-v"
      key:
        from_secret: RSYNC_KEY
