baseurl = "https://blog.leakix.net/"
languageCode = "en-us"
title = "LeakIX blog"
theme = "leakix-dark"
[pagination]
pagerSize = 5
summaryLength = 50

[permalinks]
posts = "/:year/:month/:title/"
page = "/:slug/"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Posts"
                url = "/posts/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "divider"
                weight = 3
            [[menu.main]]
                parent = "blog"
                name = "Tags"
                url = "/tags/"
                weight = 4


# Format dates with Go's time formatting
date_format = "Mon Jan 02, 2006"


# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
# Bulgarian date format is dd.mm.yyyy
#date_format = "02.01.2006"

[params]
    description     = "cat < /dev/mind > /dev/stdout"
    contactEmail    = "blog@leakix.net"
    footer          = "© 2025 LeakIX"
    googleSearch    = ""
    googleAnalytics = ""      # Google Analytics v4
    adsense         = ""
    math            = false   # best to enable this in the front matter of a page
    mermaid         = false   # best to enable this in the front matter of a page
    author          = "BloodyShell"

    # Social Media Params
    facebook   = ""
    twitter    = "https://twitter.com/leak_ix"
    youtube    = ""
    instagram  = ""
    github     = "https://github.com/LeakIX"
    pinterest  = ""
    linkedin   = "https://www.linkedin.com/company/leakix"
